[package]
name = "bilibili-api-rs"
version = "0.1.0"
authors = ["lifeich1 <lintd23@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
