name: Publish

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - uses: katyo/publish-crates@v2
      with:
        path: './bilibili-api-rs'
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        dry-run: ${{ !startsWith(github.ref, 'refs/tags/v') }}
